### ISSUE TITLE
Incompatibility with `electric-pair-mode`

### ISSUE THREAD

**Issue by joostkremers** [tbanel/uniline#3] opened 2024-10-14 14:20 UTC
There seems to be an incompatibility with `electric-pair-mode`. When I start a plain Emacs with just `uniline-mode`:

```
joost@sphinx ~$ emacs -Q -L .emacs.d/elpa/hydra-20220910.1206/ -L .emacs.d/elpa/lv-20200507.1518/ -L .emacs.d/elpa/uniline-20241008.2114/
```

Then require `uniline-mode`, go to the `*scratch*` buffer do `M-x electric-pair-mode` and then `M-x uniline-mode RET`, every pressing a cursor key gives me the following error:

```
electric-pair--with-syntax-1: Wrong type argument: characterp, right
```

(Message copied from the `*Messages*` buffer; in the minibuffer, only the error itself is printed, not the function that triggers it.) I'm not able to produce a backtrace, even with debug-on-error set...

**Comment by tbanel** [comment] 2024-10-15 08:08
I can reproduce it easily
Investigating...

**Comment by tbanel** [comment] 2024-10-15 09:25
Found!

`electric-pair-mode` makes the assumption that `self-insert-command` inserts the same character mentioned in `last-command-event`

`uniline-mode` breaks this assumption by translating keyboard commands like for instance `<left>` into UNICODE block lines.

The same bug may happen for utilities other than `electric-pair-mode`. So, I'm looking for a way to fix that independently of `electric-pair-mode`.

Stay tuned...

**Comment by tbanel** [comment] 2024-10-16 10:26
Fixed!

I used to call `self-insert-command` to insert characters, because it honors `overwrite-mode`. But `self-insert-command` does too many side-effects. I switched to `insert` which does not honor `overwrite-mode`. But an additional `delete-char` does the trick.

The overall result is that `electric-pair-mode` can no longer notice `uniline-mode` and works as expected. Except maybe that `electric-pair-mode` is not fully comfortable with the `overwrite-mode`, and `uniline-mode` needs it. Anyway, there is no longer a crash. And this can benefit to other unrelated utilities.

As a bonus, insertion of usual characters now move the cursor, as asked by @DogLooksGood.

Thanks @joostkremers for your help on this issue!
I close it. Do not hesitate to re-open it or a new one in case of something.

Have fun!

**Closed by tbanel** 2024-10-16 10:26 UTC

**Comment by joostkremers** [comment] 2024-10-16 12:42
Just tried it and yes, it works! Thank you for the work you've put into this package!

**Comment by DogLooksGood** [comment] 2024-10-16 21:09
L1936 makes it hard to customize key bindings.

    (unintern 'uniline-mode-map nil)

**Comment by tbanel** [comment] 2024-10-17 07:58
You mean line 1963?
Yes! It is meant for easing development.
When typing `M-x eval-buffer`, all Lisp code is re-loaded, except this `uniline-mode-map`. So the line you mentioned, @DogLooksGood
```lisp
(unintern 'uniline-mode-map nil)
```
ensures that 100% of the code is reloaded.
Of course, this kludge should not be included in the runtime package. I will comment it.

Thanks @DogLooksGood for looking so deeply into the code!
